replicaCount: 1

googleCloud:
  projectID: "techhack-451213"

artifactRegistry:
  repositoryName: "cwa"

dockerImage:
  name: "qp-assessment"
  tag: "latest"
  pullPolicy: "Always"

image:
  repository: "asia-south1-docker.pkg.dev/{{ .values.googleCloud.projectID }}/{{ .values.artifactRegistry.repositoryName }}/{{ .values.dockerImage.name }}"
  tag: "{{ .values.dockerImage.tag }}"
  pullPolicy: "{{ .values.dockerImage.pullPolicy }}"

service:
  type: LoadBalancer      # Type of service (LoadBalancer to expose externally)
  port: 80                # External port
  targetPort: 8091        # Internal port your app is listening on

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
