replicaCount: 1

googleCloud:
  projectID: "techhack-451213"

artifactRegistry:
  repositoryName: "cwa"

dockerImage:
  name: "qp-assessment"
  tag: "latest"
  pullPolicy: "Always"

image:
  repository: "asia-south1-docker.pkg.dev/{{ .Values.googleCloud.projectID }}/{{ .Values.artifactRegistry.repositoryName }}/{{ .Values.dockerImage.name }}"
  tag: "{{ .Values.dockerImage.tag }}"
  pullPolicy: "{{ .Values.dockerImage.pullPolicy }}"

service:
  type: LoadBalancer      # Type of service (LoadBalancer to expose externally)
  port: 80                # External port
  targetPort: 8091        # Internal port your app is listening on

resources:
  requests:
    memory: "128Mi"   # Reduced from 256Mi to 128Mi
    cpu: "100m"       # Reduced from 250m to 100m
  limits:
    memory: "256Mi"   # Reduced from 512Mi to 256Mi
    cpu: "200m"       # Reduced from 500m to 200m
