replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/techhack-451213/cwa/qp-assessment
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer      # Type of service (LoadBalancer to expose externally)
  port: 80                # External port
  targetPort: 8091        # Internal port your app is listening on

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m