apiVersion: v1
kind: ConfigMap
metadata:
  name: create-dbs-configmap
data:
  create-dbs.sh: |
    #!/bin/bash
    set -e

    PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER CWADB WITH ENCRYPTED PASSWORD 'CWADBpass';
      CREATE DATABASE CWADB;
      GRANT ALL PRIVILEGES ON DATABASE CWADB TO CWADB;
    EOSQL