apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  # External port
      targetPort: 5432  # Internal PostgreSQL port
  clusterIP: None  # This makes it a headless service (recommended for StatefulSet)