replicaCount: 2

image:
  repository: asia-south1-docker.pkg.dev/techhack-380811/cwa/cwa
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "250m"   # 0.25 vCPU
    memory: "512Mi" # 512 MiB
  limits:
    cpu: "500m"   # 0.5 vCPU
    memory: "1Gi" # 1 GiB
