replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/techhack-451213/cwa/qp-assessment
  tag: latest
  pullPolicy: Always

service:
  name: my-app
  port: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

