apiVersion: v1
kind: ConfigMap
metadata:
  name: app-prop-cm
data:
  spring.profiles.active: "dev"
  spring.datasource.url: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/CWADB"
  spring.datasource.username: "CWADB"
  spring.datasource.password: "CWADBpass"
  spring.datasource.driver-class-name: "org.postgresql.Driver"
  spring.jpa.database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.show-sql: "true"
  server.port: "8091"
  spring.application.name: "qp-assessment"