apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-my-app   # Directly using .Release.Name to construct the name
  labels:
    app: {{ .Release.Name }}         # Label with the release name
spec:
  replicas: {{ .Values.replicaCount }}  # Number of replicas (taken from values.yaml)
  selector:
    matchLabels:
      app: {{ .Release.Name }}         # Selector label to associate the deployment with the pods
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}       # Label for the pod
    spec:
      containers:
        - name: my-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Docker image and tag
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }}  # Port the container will expose
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
