apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}  # Service name will be the same as the release name
spec:
  selector:
    app: {{ .Release.Name }}  # Selects the pods with the matching label
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # External port (exposed to the outside world)
      targetPort: {{ .Values.service.targetPort }}  # Internal port the app listens on
  type: {{ .Values.service.type }}  # LoadBalancer or ClusterIP, depending on your values.yaml